package com.example.training.hidden;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

public class HiddenClassWithASM {

  public static void main(String[] args) throws Throwable {
    byte[] classBytes = generateWithASM();

    MethodHandles.Lookup lookup = MethodHandles.lookup();

    // Define hidden class from the generated bytes
    Class<?> hiddenClass = lookup
        .defineHiddenClass(classBytes, true, MethodHandles.Lookup.ClassOption.NESTMATE)
        .lookupClass();

    System.out.println("Hidden: " + hiddenClass.isHidden());
    System.out.println("Name:   " + hiddenClass.getName());

    MethodHandles.Lookup hiddenLookup =
        MethodHandles.privateLookupIn(hiddenClass, lookup);

    MethodHandle handle = hiddenLookup.findStatic(
        hiddenClass,
        "message",
        MethodType.methodType(String.class)
    );

    String result = (String) handle.invokeExact();
    System.out.println("Result: " + result);
  }

  /**
   * Generates a class equivalent to:
   * <p>
   * public class HiddenGenerated { public static String message() { return "Hello from hidden class with ASM"; } }
   */
  private static byte[] generateWithASM() {
    String className = "com/example/training/hidden/HiddenGenerated";

    ClassWriter cw = new ClassWriter(0);
    // Use Java 11 bytecode version (safe on newer JDKs)
    cw.visit(Opcodes.V11,
        Opcodes.ACC_PUBLIC,
        className,
        null,
        "java/lang/Object",
        null);

    // Default constructor
    MethodVisitor ctor = cw.visitMethod(
        Opcodes.ACC_PUBLIC,
        "<init>",
        "()V",
        null,
        null
    );
    ctor.visitCode();
    ctor.visitVarInsn(Opcodes.ALOAD, 0);
    ctor.visitMethodInsn(
        Opcodes.INVOKESPECIAL,
        "java/lang/Object",
        "<init>",
        "()V",
        false
    );
    ctor.visitInsn(Opcodes.RETURN);
    ctor.visitMaxs(1, 1);
    ctor.visitEnd();

    // public static String message()
    MethodVisitor mv = cw.visitMethod(
        Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
        "message",
        "()Ljava/lang/String;",
        null,
        null
    );
    mv.visitCode();
    mv.visitLdcInsn("Hello from hidden class with ASM");
    mv.visitInsn(Opcodes.ARETURN);
    mv.visitMaxs(1, 0);
    mv.visitEnd();

    cw.visitEnd();

    return cw.toByteArray();
  }
}
