/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_training_g1_G1RegionPinningDemo */

#ifndef _Included_com_example_training_g1_G1RegionPinningDemo
#define _Included_com_example_training_g1_G1RegionPinningDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_training_g1_G1RegionPinningDemo
 * Method:    holdArrayCritical
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_example_training_g1_G1RegionPinningDemo_holdArrayCritical
  (JNIEnv *, jclass, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
